---
- name: Update yum package cache
  yum:
    name: "*"
    state: latest

- name: Install required packages
  yum:
    name:
      - docker
      - git
    state: present

- name: Ensure docker CLI plugins directory exists
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker Compose v2 plugin binary
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.39.1/docker-compose-linux-x86_64

    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: '0755'
  become: yes

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
  become: yes

