# Project settings
user: ec2-user
user_group: ec2-user
project_root: "/local/home/ghaniis/ans-terra"

# Dynamic IP resolution
gitlab_server_ip: "{{ hostvars[groups['gitlab'][0]]['ansible_host'] | default(groups['gitlab'][0]) }}"
