# GitLab Server Configuration - Dynamic IP from inventory
gitlab_hostname: "{{ gitlab_server_ip }}"
gitlab_external_url: "http://{{ gitlab_server_ip }}"
# GitLab Docker settings
gitlab_image: "gitlab/gitlab-ce:latest"
gitlab_container_name: "gitlab"

# GitLab directories
gitlab_config_dir: "/srv/gitlab/config"
gitlab_logs_dir: "/srv/gitlab/logs"
gitlab_data_dir: "/srv/gitlab/data"

# GitLab ports 
gitlab_http_port: 80
gitlab_https_port: 443
gitlab_ssh_port: 2222

# Docker compose configuration
docker_compose_file: "/srv/gitlab/docker-compose.yml"
