# ansible/playbook.yml
- name: Provision Dockerized Web App
  hosts: webserverAL2
  become: yes

  tasks:
    - name: Update yum package cache
      yum:
        name: "*"
        state: latest

    - name: Install docker & git on host
      yum:
        name:
          - docker
          - git
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Copy app files to server
      copy:
        src: ../docker-app/
        dest: /home/ec2-user/docker-app
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Build Docker image
      docker_image:
        name: myapp
        build:
          path: /home/ec2-user/docker-app
        source: build
        state: present

    - name: Run Docker container
      docker_container:
        name: myapp
        image: myapp
        state: started
        ports:
          - "80:5000"
        restart_policy: always

