---
- name: Ensure GitLab Runner config directory exists
  file:
    path: "{{ gitlab_runner_config_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Deploy GitLab Runner with Docker Compose
  template:
    src: docker-compose-runner.yml.j2
    dest: "{{ docker_compose_file }}"
  become: yes

- name: Start GitLab Runner
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_file | dirname }}"
    recreate: always
    remove_orphans: yes
    pull: always
  become: yes

- name: Wait for GitLab Runner container to be ready
  wait_for:
    timeout: 30

- name: Register GitLab Runner
  command: >
    docker exec {{ gitlab_runner_container_name }}
    gitlab-runner register
    --non-interactive
    --url "{{ gitlab_runner_url }}"
    --registration-token "{{ gitlab_runner_token }}"
    --description "{{ gitlab_runner_description }}"
    --executor "{{ gitlab_runner_executor }}"
    --docker-image "{{ gitlab_runner_docker_image }}"
  become: yes

